################### BUILD AND RUN THIS DOCKER FILE ############################

### BUILD IMAGE

# docker build -t pisca-sing -f Dockerfile_sing .

### TEST IMAGE

# docker run -v ~/dev/beast-icr/pisca-branch:/mnt --rm pisca-branch-master flipflop.xml

### UPLOAD TO DOCKER

# docker tag pisca-branch-master rachelicr/pisca-branch-master
# docker push rachelicr/pisca-branch-master

### Pull DOWN FROM DOCKER and run

# docker pull rachelicr/pisca-branch-master
# docker run -v ~/your/path/to/xml/file:/mnt --rm pisca-branch-master your.xml

# docker run -it --privileged pisca-sing
#################################################################################
FROM bitnami/minideb:stretch
#MAINTAINER Johannes Köster <johannes.koester@tu-dortmund.de>
ADD . /tmp/repo
WORKDIR /tmp/repo
ENV PATH /opt/conda/bin:${PATH}
ENV LANG C.UTF-8
ENV SHELL /bin/bash
RUN /bin/bash -c "install_packages wget bzip2 ca-certificates gnupg2 squashfs-tools git && \
    wget -O- https://neuro.debian.net/lists/xenial.us-ca.full > /etc/apt/sources.list.d/neurodebian.sources.list && \
    wget -O- https://neuro.debian.net/_static/neuro.debian.net.asc | apt-key add - && \
    install_packages singularity-container && \
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda3-latest-Linux-x86_64.sh && \
    conda create -c conda-forge -n snakemake bioconda::snakemake bioconda::snakemake-minimal --only-deps && \
    conda clean --all -y && \
    source activate snakemake && \
    which python && \
    pip install ."
RUN echo "source activate snakemake" > ~/.bashrc
ENV PATH /opt/conda/envs/snakemake/bin:${PATH}