################### BUILD AND RUN THIS DOCKER FILE ############################

### BUILD IMAGE
# docker build -t rachelicr/env-pisca-v2 -f .devcontainer/Dockerfile .

### USE IMAGE
# ctrl-sh-p in vscode and select the image

### PUSH IMAGE
# docker push rachelicr/env-pisca-v1

#################################################################################
# Image downloaded with advice from: # https://stackoverflow.com/questions/54437030/how-can-i-create-a-docker-image-to-run-both-python-and-r
# and here: https://github.com/dr-joe-wirth/phantasm/blob/master/docker_build_files/Dockerfile
FROM r-base:4.3.2
RUN apt-get -y update
RUN apt-get update && apt-get install -y --no-install-recommends build-essential r-base r-cran-randomforest python3.10 python3-pip python3-setuptools python3-dev

# install required R libraries
RUN R -e "install.packages('ape',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('jsonlite',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('data.table',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('ggplot2',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('cowplot',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('HDInterval',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('lubridate',dependencies=TRUE, repos='http://cran.rstudio.com/')"
# And from BIOCMANAGER
RUN R -e "install.packages('BiocManager',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "BiocManager::install('treeio')"
RUN R -e "BiocManager::install('ggtree')"

# install required python modules
WORKDIR /app
ADD requirements.txt .
# installing python libraries
RUN pip3 install -r requirements.txt

COPY . /app
